/aruco_node:
  ros__parameters:
    marker_size: .05
    aruco_dictionary_id: DICT_6X6_250
    image_topic: /camera/color/image_raw
    camera_info_topic: /camera/color/camera_info
    camera_frame: camera_link